### ISSUE TITLE
optional env deck variables

### ISSUE THREAD

**Issue by zekth** [Kong/deck#1024]
Currently all env variables need to be set when using deck, however it creates a problem with some cases and deck usages. Take this as an example:

```yaml
plugins:
- name: acme
  config:
    account_email: ${{ env "DECK_ACME_ACCOUNT_EMAIL" }}
    api_uri: ${{ env "DECK_ACME_API_URI" }}
    eab_kid: ${{ env "DECK_ACME_EAB_KEY_ID" }}
    eab_hmac_key: ${{ env "DECK_ACME_EAB_SECRET" }}
    ${{- if env "DECK_ACME_ACCOUNT_KEY" }}
    account_key: ${{ env "DECK_ACME_ACCOUNT_KEY" }}
    ${{- end }}
    allow_any_domain: true
    tos_accepted: true
    storage: redis
    storage_config:
      redis:
        host: ${{ env "DECK_REDIS_HOST" }}
        port: 6379
        auth: ${{ env "DECK_REDIS_KEY" }}
        ssl: true
        ssl_verify: false
```
So we have potential cases where `DECK_ACME_ACCOUNT_KEY` is set, in the helm context when deploying the deck config. However by this `if` condition it makes the `deck file merge` unusable because it's not a valid `yaml` file.

What we can do is introducing `envOptional` to get rid of this problem. So `envOptional` would just output an empty string `''`; in addition to this we can add also a `nullFallback` function to return `null` in case of empty string. So in this case would have a template like this:
```yaml
plugins:
- name: acme
  config:
...
    account_key: ${{ envOptional "DECK_ACME_ACCOUNT_KEY" }}
```
will output
```yaml
```yaml
plugins:
- name: acme
  config:
...
    account_key: ''
```
with `nullFallback` we would have this
```yaml
plugins:
- name: acme
  config:
...
    account_key: ${{ envOptional "DECK_ACME_ACCOUNT_KEY" | nullFallback }}
```
will output
```yaml
```yaml
plugins:
- name: acme
  config:
...
    account_key: null
```

And this would solve many of templating issues.
