### ISSUE TITLE
Unable to diff or sync a control plane with custom plugins since deck v1.27.0

### ISSUE THREAD

**Issue by EDeijl** [Kong/deck#1035]
I'm running the specified below config (names changed to more generic names), which I generated with `deck dump` on deck version 1.26.1.

running `deck sync` or `deck diff` with this config worked fine on `1.26.1` but on `1.27.0` I get the following error:

```
Error: building state: add defaults to plugin 'auth-plugin': retrieve schema for auth-plugin from Kong: HTTP status 404 (message: "no plugin-schema for 'auth-plugin'")
```
auth plugin is a custom lua plugin, for which support just was enabled in the konnect interface. 

The plugin exists in the interface, and the schema file has been uploaded and is valid and the plugin runs correctly in the runtime instances.

If I dump the config with 1.27.0 it will only change the `_konnect.runtime_group_name` property to be named `_konnect.control_plane_name` and still refuses to sync or diff with the same error.

config I'm running:
```yaml
_format_version: "3.0"
_konnect:
  runtime_group_name: Remote API # If I do `dump` with 1.27.0 this is the only line changed
services:
- connect_timeout: 60000
  enabled: true
  host: api.default.svc.cluster.local
  name: api
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: api
    path_handling: v0
    paths:
    - /
    plugins:
    - config:
        authorization_endpoint: http://auth-server.default.svc.cluster.local./auth
      enabled: true
      instance_name: auth-plugin
      name: auth-plugin
      protocols:
      - http
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  tags:
  - remote-api
  write_timeout: 60000
```
