### ISSUE TITLE
deck file render - env substition does not work with string values  

### ISSUE THREAD

**Issue by martijndxc** [Kong/deck#1207]
When running deck file render on a yaml file containing env substitions the substition puts the name of the variable in the configuration value instead of the value. Note when using any of the functions such as toBool then the substition works as expected.

Deck version: decK v1.29.2 (77682ca) - also tried v1.33.0 and got the same results
OS: Linux - Tested on both Ubuntu 22.04 and Ubuntu 22.04 server with latest updates applied

Example Config file
```
_format_version: "3.0"
plugins:
- config:
    echo_downstream: ${{ env "DECK_ECHO_DOWNSTREAM" | toBool }}
    generator: uuid
    header_name: ${{ env "DECK_HEADER_NAME"}}
  enabled: true
  name: correlation-id
  protocols:
  - grpc
  - grpcs
  - http
  - https
```

The variables have been exported:
```
export DECK_HEADER_NAME=X-Request-ID
export DECK_ECHO_DOWNSTREAM=true
```

And verified by running the env command:
```
> env | grep DECK
DECK_HEADER_NAME=X-Request-ID
DECK_ECHO_DOWNSTREAM=true 
``` 

Then I execute deck using the command **'deck file render kong-config.yaml'**
Which returns the output:
```
_format_version: "3.0"
plugins:
- config:
    echo_downstream: false
    generator: uuid
    header_name: DECK_HEADER_NAME
  enabled: true
  name: correlation-id
  protocols:
  - grpc
  - grpcs
  - http
  - https
```

As you can see "header_name: DECK_HEADER_NAME" contains the name of the variable but I expected it to contain "header_name: X-Request-ID"
