### ISSUE TITLE
Deck convert from 2.x to 3.x does not handle the escape characters in the regex paths

### ISSUE THREAD

**Issue by shambhand** [Kong/deck#1310]
Input 
``` yaml
  routes:
  - https_redirect_status_code: 426
    methods:
    - POST
    name: excelReader-route
    path_handling: v0
    paths:
    - /excelReader/([^\/]+)
 ```

`deck file convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file {input_file} --output-file {output_file}`

Expected output:
``` yaml
  routes:
  - https_redirect_status_code: 426
    methods:
    - POST
    name: excelReader-route
    path_handling: v0
    paths:
    - /excelReader/([^/]+)
 ```
 
 After converted file from 2.x to 3.x output, while syncing got an below error
 
 ``` 
 while processing event: Create route excelReader-route failed: HTTP status 400 (message: "validation error")
 ```
