### ISSUE TITLE
deck file lint: `Error: accepts 1 arg(s), received 0`

### ISSUE THREAD

**Issue by j796160836** [Kong/deck#1326]
Hi, I'm newbie with Kong and I'm trying to build yaml linter to my CI/CD pipeline.
Here is my reproduce steps.

I do the simplest example `kong.yaml`
```yaml
_format_version: "3.0"
services:
- name: example-service
  enabled: true
  host: example.com
  path: /
  port: 443
  protocol: https
  connect_timeout: 60000
  read_timeout: 60000
  write_timeout: 60000
  retries: 5
  routes:
  - name: example-route
    https_redirect_status_code: 426
    path_handling: v0
    paths:
    - /example
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
```

and I run this command with docker

```shell
docker run --rm -v ./kong.yaml:/kong.yaml kong/deck:v1.34.0 file lint --format yaml --config kong.yaml
```

and it complains

```
Error: accepts 1 arg(s), received 0
```

How can I do with yaml? or it just a linter bug?
Any suggestion is appreciated, thanks.

**Comment by Tieske** [comment]
`--config` is for the deck configuration, not the declarative state file.

So then it becomes this:
```
docker run --rm -v ./kong.yaml:/kong.yaml kong/deck:v1.34.0 file lint --format yaml --state kong.yaml
```

But then still it requires a rule-set file (containing the linting rules to apply on the file). Check `deck file lint --help`.

```
docker run --rm -v ./kong.yaml:/kong.yaml kong/deck:v1.34.0 file lint --format yaml --state kong.yaml <your-linting-rules.yml>
```

**Comment by j796160836** [comment]
Oh, I found the reference 
https://konghq.com/blog/product-releases/deck-file-linting

So I add a `ruleset.yaml`

**ruleset.yaml**
```yaml
rules: {}
```

and change the command

```bash
docker run --rm -v ./kong.yaml:/kong.yaml -v ./ruleset.yaml:/ruleset.yaml kong/deck:v1.34.0 file lint --format yaml --config /kong.yaml ruleset.yaml
```

and got the result

```
fail_count: 0
results: []
total_count: 0
```

**Comment by j796160836** [comment]
May I ask...How to lint the `kong.yaml` to prevent sloppy mistakes?
For example, `services` lack the essential key `host` and `path`.

**Comment by rspurgeon** [comment]
@j796160836 Unfortunately at this time we don't have a good example ruleset file for decK files. This is something I will share if it is built at a later time.  In the meantime, users are required to build a ruleset file themselves with the rules they wish to enforce.

the `deck file lint` command utilizes the Vacuum GoLang based library to implement the linting logic (https://github.com/daveshanley/vacuum). 

Thus, the ruleset file should conform to the rules supported by that library, which in turn supports Spectral linting rule format.

I thought I would provide you with some basic examples to get started.

Here is a sample decK file:
```
_format_version: "3.0"
services:
  - host: tasks.example.com
    name: task-api
    path: /
    protocol: https
    routes:
    - methods:
      - GET
      name: task-api_gettasks
      paths:
      - ~/tasks$
  - host: tasks2.example.com
    name: task2-api
    path: /
    protocol: http
    routes:
    - methods:
      - GET
      name: task2-api_gettasks
      paths:
      - ~/tasks2$
```

Here is a sample ruleset file, with one rule, that validates that all services utilize the `https` protocol in their `protocol` key:

```
rules:
  check-https:
    description: "Ensure services only use https for communication"
    given: "$.services[*].protocol"
    severity: error
    then:
      function: pattern
      functionOptions:
        match: "^https$"
```

When running this w/ `deck file lint`, you should see the following:
```
> deck file lint -s kong.yaml rules.yaml
Linting Violations: 1
Failures: 1

[error][16:15] Ensure services only use https for communication: `http` does not match the expression `^https$`
```

I hope this helps you get started with the tool.  For information on supported functions, rules and ruleset, please see this section of the documentation
https://quobix.com/vacuum/functions/core/
