### ISSUE TITLE
deck gateway diff no masking on existing configuration

### ISSUE THREAD

**Issue by Puwanut** [Kong/deck#1379]
My kong yaml configuration using environment variables with deck reference format, but I found that existing configuration on Kong Gateway not be masked. The masked text is applied on local configuration only.

Version
Kong gateway: 3.7.1
Deck: 1.39.3

This is some part of my configuration 
```
- config:
    batch_flush_delay: null
    batch_span_count: null
    connect_timeout: 1000
    endpoint: http://localhost:9999
    header_type: w3c
    headers:
      Authorization: Bearer ${{ env "DECK_OTEL_APM_TOKEN" }}
    http_response_header_for_traceid: null
    propagation:
      clear: null
      default_format: w3c
      extract: null
      inject: null
    queue:
      initial_retry_delay: 0.01
      max_batch_size: 1
      max_bytes: null
      max_coalescing_delay: 1
      max_entries: 10000
      max_retry_delay: 60
      max_retry_time: 60
    read_timeout: 5000
    resource_attributes:
      deployment.environment: dev
      service.name: xxx.service
    sampling_rate: 1
    send_timeout: 5000
  enabled: true
  instance_name: OpenTelemetry-xxx.service
  name: opentelemetry
  protocols:
  - grpc
  - grpcs
  - http
  - https
```
![image](https://github.com/user-attachments/assets/635edec6-cca3-463e-8c7d-44bd49f20612)
