### ISSUE TITLE
2.x to 3.x migration with Consumer Groups

### ISSUE THREAD

**Issue by mheap** [Kong/deck#1383]
Upgrading from 2.8.4 to 3.4.x does not work as expected.

This config works fine on 2.8:

```yaml
_format_version: "1.0"
services:
  - name: "httpbin-service"
    host: "httpbin.org"
    path: "/anything"
    port: 80
    protocol: "http"
    routes:
      - name: "httpbin-route"
        methods:
          - "GET"
        paths:
          - "/anything"
    plugins:
      - name: acl
        protocols:
          - grpc
          - grpcs
          - http
          - https
        config:
          allow:
            - apples-1_consumers
          deny: null
          hide_groups_header: false
        enabled: true
      - name: key-auth
        protocols:
          - grpc
          - grpcs
          - http
          - https
        config:
          anonymous: null
          hide_credentials: false
          key_in_body: false
          key_in_header: true
          key_in_query: false
          key_names:
            - x-banana-client-id
          run_on_preflight: true
        enabled: true
      - name: rate-limiting-advanced
        protocols:
          - grpc
          - grpcs
          - http
          - https
        config:
          consumer_groups:
            - apples-1-gold
            - apples-1-silver
            - apples-1-bronze
          dictionary_name: kong_rate_limiting_counters
          enforce_consumer_groups: true
          header_name: null
          hide_client_headers: false
          identifier: consumer
          limit:
            - 10
          window_size:
            - 1
          namespace: tR7X50DIbxUtdMXn8jWYZFa4TnsiSTrZ
          path: null
          retry_after_jitter_max: 0
          strategy: local
          sync_rate: -1
          window_type: sliding
        enabled: true
consumers:
  - username: "apple-consumer-0"
    keyauth_credentials:
      - key: "key-0"
    groups:
      - name: "apples-1-gold"
    acls:
      - group: "apples-1_consumers"
  - username: "apple-consumer-1"
    keyauth_credentials:
      - key: "key-1"
    groups:
      - name: "apples-1-silver"
    acls:
      - group: "apples-1_consumers"
  - username: "apple-consumer-2"
    keyauth_credentials:
      - key: "key-2"
    groups:
      - name: "apples-1-bronze"
    acls:
      - group: "apples-1_consumers"
consumer_groups:
  - name: "apples-1-gold"
    plugins:
      - name: rate-limiting-advanced
        config:
          limit:
            - 2000
          retry_after_jitter_max: 0
          window_size:
            - 1
          window_type: sliding
  - name: "apples-1-silver"
    plugins:
      - name: rate-limiting-advanced
        config:
          limit:
            - 1000
          retry_after_jitter_max: 0
          window_size:
            - 1
          window_type: sliding

  - name: "apples-1-bronze"
    plugins:
      - name: rate-limiting-advanced
        config:
          limit:
            - 500
          retry_after_jitter_max: 0
          window_size:
            - 1
          window_type: sliding
```

Run `deck file convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file decks/consumer_group_2.8.yaml --output-file decks/consumer-group_3.4.yaml`

Syncing the converted file creates the RLA plugins as global rather than scoped to a consumer group. This may be related to #1005, but the UI also shows the plugins as global.

Acceptance criteria:

- [ ] The 2.8 config can be converted to a 3.4 config using `deck`
- [ ] Created plugins are scoped to consumer groups rather than being global
