### ISSUE TITLE
Doing a "deck diff" on some statefiles brings a change to the "created_at" attribute

### ISSUE THREAD

**Issue by zraider7** [Kong/deck#142]
Deck version: 1.1.0
Kong version:  1.3.0.2-enterprise-edition

This file was created by doing a dump on a dev cluster, splitting into files with tags and pushing to a test cluster.
Here is an example of the statefile I am running:
```
_format_version: "1.1"
_info:
  select_tags:
      - managed-by-deck
      - fun-aggregator
services:
- connect_timeout: 60000
  host: fun-aggregator.upstream.kong
  name: fun-aggregator
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - hosts:
    - funcounts-dev.cl.local
    id: aefa6011-582f-4781-90ef-08f9b238359a
    methods:
    - GET
    paths:
    - /test
    preserve_host: true
    protocols:
    - http
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
upstreams:
- name: fun-aggregator.upstream.kong
  algorithm: round-robin
  slots: 1000
  healthchecks:
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 5
        successes: 1
      http_path: /state/instances
      https_verify_certificate: false
      type: http
      timeout: 1
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        tcp_failures: 0
        timeouts: 0
        interval: 0
    passive:
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 0
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        tcp_failures: 0
        timeouts: 0
  hash_on: none
  hash_fallback: none
  targets:
  - target: foo.constoso.iocal:443
    weight: 100
```

It syncs fine, but after running a deck diff on it, it returns this:

```
deck diff -s fun-aggregator.yaml --parallelism 1
updating upstream fun-aggregator.upstream.kong  {
   "algorithm": "round-robin",
-  "created_at": 1.586548039e+09,
   "hash_fallback": "none",
   "hash_on": "none",
   "hash_on_cookie_path": "/",
   "healthchecks": {
     "active": {
       "concurrency": 10,
       "healthy": {
         "http_statuses": [
           200,
           302
         ],
         "interval": 5,
         "successes": 1
       },
       "http_path": "/state/instances",
       "https_verify_certificate": false,
       "timeout": 1,
       "type": "http",
       "unhealthy": {
         "http_failures": 0,
         "http_statuses": [
           429,
           404,
           500,
           501,
           502,
           503,
           504,
           505
         ],
         "interval": 0,
         "tcp_failures": 0,
         "timeouts": 0
       }
     },
     "passive": {
       "healthy": {
         "http_statuses": [
           200,
           201,
           202,
           203,
           204,
           205,
           206,
           207,
           208,
           226,
           300,
           301,
           302,
           303,
           304,
           305,
           306,
           307,
           308
         ],
         "successes": 0
       },
       "unhealthy": {
         "http_failures": 0,
         "http_statuses": [
           429,
           404,
           500,
           501,
           502,
           503,
           504,
           505
         ],
         "tcp_failures": 0,
         "timeouts": 0
       }
     }
   },
   "id": "25005808-f5a2-4229-bcdf-2f6206a28b01",
   "name": "fun-aggregator.upstream.kong",
   "slots": 1000,
   "tags": [
     "managed-by-deck",
   ]
 }

updating target foo.constoso.iocal:443 for upstream 25005808-f5a2-4229-bcdf-2f6206a28b01  {
-  "created_at": 1.586548039485e+09,
   "id": "9733279e-0049-4ffb-9a2b-7964274d738b",
   "tags": [
     "managed-by-deck",
   ],
   "target": "foo.constoso.iocal:443",
   "upstream": {
     "id": "25005808-f5a2-4229-bcdf-2f6206a28b01"
   },
   "weight": 100
 }

updating service fun-aggregator  {
   "connect_timeout": 60000,
-  "created_at": 1.586548039e+09,
   "host": "fun-aggregator.upstream.kong",
   "id": "98c70c9d-9d7b-4749-927a-4f9e62ba9ea5",
   "name": "fun-aggregator",
   "port": 80,
   "protocol": "http",
   "read_timeout": 60000,
   "retries": 5,
   "tags": [
     "managed-by-deck",
   ],
-  "updated_at": 1.586548039e+09,
   "write_timeout": 60000
 }

updating route aefa6011-582f-4781-90ef-08f9b238359a  {
-  "created_at": 1.586548008e+09,
   "hosts": [
     "funcounts-dev.cl.local"
   ],
   "https_redirect_status_code": 426,
   "id": "aefa6011-582f-4781-90ef-08f9b238359a",
   "methods": [
     "GET"
   ],
   "paths": [
     "/test"
   ],
   "preserve_host": true,
   "protocols": [
     "http"
   ],
   "regex_priority": 0,
   "service": {
     "id": "98c70c9d-9d7b-4749-927a-4f9e62ba9ea5"
   },
   "strip_path": true,
   "tags": [
     "managed-by-deck",
   ],
-  "updated_at": 1.586548008e+09
 }

Summary:
  Created: 0
  Updated: 4
  Deleted: 0
```

**Comment by zraider7** [comment]
We would like our cd pipeline to notify us if there is any config drift and this is kinda a false positive. The worse thing is that it only happens on some state files and not others. If I am doing/understanding something wrong, lemme know! :)

**Comment by hbagdi** [comment]
Stdout is useful only for humans. decK didn't have this issue before but it does have it after a major refactor was done a few months ago.

For you problem, please use the following flag for `deck diff`:
```
      --non-zero-exit-code   return exit code 2 if there is a diff present,
                             exit code 0 if no diff is found,
                             and exit code 1 if an error occurs.

```

**Comment by zraider7** [comment]
Can confirm that it comes back with an exit code of 2, which is awesome. So was this a change in kong or kong-deck? I am hoping to basically not return the "Created_at" attribute so that it will return a 0 again.

**Comment by hbagdi** [comment]
Ah, I see how that flag won't solve your problem because of the false positive.
This is an issue with decK.
I'll fix it.

**Comment by zraider7** [comment]
Much appreciated and thanks for the quick responses!

**Comment by hbagdi** [comment]
I can't reproduce this. Are you sure you are using decK 1.1.0?

**Comment by zraider7** [comment]
Yeah, when I run "deck version", here is what I get:
decK v1.1.0 (acdb161)

**Comment by zraider7** [comment]
And that's the really odd thing, I have about 8 state files and on 2 of them, it returns the diff with the create_at attribute. Not sure why

**Comment by hbagdi** [comment]
Can you share all eight files? It might a bug in a multi-file state implementation (although very unlikely).

**Comment by zraider7** [comment]
Absolutely, will get that up by EOD today. Sorry for the delay

**Comment by acigolotti** [comment]
Hello, 

I'm currently testing decK and ran into the same issue,

Since I have only 1 state file with 40-ish services and 50-ish routes and experienced the « problem » with 9 of my routes, I don't think the problem is related to the number of state file you have.

After searching in the code, making diffs between declarations and queries' responses from verbose mode, the only thing I found is that the response from Kong's routes returns an empty array for the methods, instead of null like the other routes.

It might not be the exact same issue as it also affects upstreams, targets and services for the op but I assume it's due to the fields not being serialized in the state file and so represent nulls but are empty in Kong.

I don't know enough Go to fix it myself, hope this will help!

Keep up the good work!

**Comment by hbagdi** [comment]
> After searching in the code, making diffs between declarations and queries' responses from verbose mode, the only thing I found is that the response from Kong's routes returns an empty array for the methods, instead of null like the other routes.

Interesting. That would explain the behavior for route but not for other entities.

@acigolotti Can you share some reproducible steps please?

**Comment by acigolotti** [comment]
First, I've tried to find why some routes have this, but no luck.
I use kong since 0.11 with konga for the UI and some route where created from there and other from curl, this may be it, or the consequence of an update, migration or whatever, I can't really tell who did what...

I can moreover reproduce it by doing those steps:

``` shell
http post :8001/services name=service.name.local host=service.host.local -f
http post :8001/services/service.name.local/routes name=route.name.local hosts=route.hosts.local -f
http patch :8001/routes/route.name.local methods:='[]' --json
deck dump
deck diff
```

I've tried with `tags` and it works too, but I don't use tags and the op does, so it's probably not the same issue.

I feel like I should just sync the state file which will clean-up all empty arrays back to null.
It's probably not worth your time to add something to compare empty set to null ones

**Comment by hbagdi** [comment]
This is a bug in Kong, it should accept an empty methods array in such a case. I'll report that to `kong/kong`.

Are you sure this is the root cause of this problem?
From what others have reported, it seems that there is something else at play. I've not been able to figure out as to what that is.

**Comment by mmorel-35** [comment]
We do meet the same issue with the distributed configuration of our services. What I can see is that when you define your configuration file, you don't define the creation and update date fields. Then when you persist it Kong defining them. And when you do the diff those fields are returned valued by end-point. Maybe is there somewhere a too deep comparison between the file and the stored versions ?

**Comment by hbagdi** [comment]
If anyone can share some reproducible steps for this issue, that would be greatly appreciated!

**Comment by mmorel-35** [comment]
Do you have tests that makes a diff between a state file with several selected tags (3 for example) which doesn't have dates on service, plugin and route with a response from kong that returns a response body that has those dates ?

**Comment by luccamendonca** [comment]
Hey @hbagdi,

It seems we were able to find at least **one** cause for this issue and as odd as it may look, doesn't seem to be related to the `created_at` or `updated_at` fields.

Looking at [this playground code](https://play.golang.org/p/oTlpYMxbKkg) we can see that `reflect.DeepEqual` doesn't account for the order of slice elements, therefore it should return `false` even both the slices have the same content.

We noticed this when comparing the following `kong.Plugin` entities, under `state/types.go` on `func (p1 *Plugin) EqualWithOpts()` and the entities had the exact same content although their `Tags` had a different order.

Running `deck diff` using a `state` we had just generated, we achieved the following:

```go
p1Copy := p1.Plugin.DeepCopy()
(...)
Tags: []*string{
  &"gatewayoperatornnewexample-metal",
  &"provision",
},


p2Copy := p2.Plugin.DeepCopy()
(...)
Tags: []*string{
  &"provision",
  &"gatewayoperatornnewexample-metal",
},
```

And then `reflect.DeepEqual` returned false, therefore adding the `Updated` event to the loop.

Maybe this is a good starting point :)

I'll keep digging from my side anyway as this diff will be really important for our project.


Thanks!

**Comment by hbagdi** [comment]
> Looking at this playground code we can see that reflect.DeepEqual doesn't account for the order of slice elements, therefore it should return false even both the slices have the same content.

 Yes, I'm aware and there are a bunch of places where arrays are being compared. I wanted to do sorting and then compare but avoided doing it for so long because it never created a problem. If you can confirm this is indeed the case, I can take a closer look. Thank you for you hard work and dedication here, @luccamendonca!

**Comment by luccamendonca** [comment]
For our specific use-case we were able to mitigate all of those unwanted diffs by sorting the `Tags` field. We added a simple sorting function on the `diff/utils.go`, as follows:

```go
func sortSlicePtr(list []*string) {
	sort.SliceStable(list, func(i, j int) bool {
		return *list[i] < *list[j]
	})
}
```

And used it on ```diff/service.go```, for example:

```go
sortSlicePtr(currentService.Tags)
sortSlicePtr(serviceCopy.Tags)

// found, check if update needed
if !currentService.EqualWithOpts(serviceCopy, false, true) {
	return &Event{
		Op:     crud.Update,
		Kind:   "service",
		Obj:    serviceCopy,
		OldObj: currentService,
	}, nil
}
```

Of course, this was just a tiny PoC to make sure the sorting would help with the issue; it would be probably a better idea to create a prettier and broader abstraction of the sorting mechanism.

Another point to bear in mind is that we still see `-  "created_at"` on the "human" diff string even when sorting the tags. A good example is as follows, after running `go run main.go diff --skip-consumers`:

```diff
updating service gatewayoperatornnewexample-metal  {
   "connect_timeout": 30001,
-  "created_at": 1.595339873e+09,
   "host": "dummy.net",
   "id": "388cf4d2-08ad-491c-982c-baf47529da69",
   "name": "dummy-service",
   "port": 80,
   "protocol": "http",
-  "read_timeout": 30000,
+  "read_timeout": 30001,
   "retries": 0,
   "tags": [
     "tag1",
     "tag2"
   ],
-  "updated_at": 1.595339873e+09,
   "write_timeout": 30000
 }
```
```
Summary:
  Created: 0
  Updated: 1
  Deleted: 0
```

I've updated the `read_timeout` field and the `gojsondiff` tool seems to still see a diff on the `date` fields, so the sorting wouldn't completely change the behavior pointed out on this issue.
