### ISSUE TITLE
Plugin configuration containing arrays not syncing

### ISSUE THREAD

**Issue by mattburton** [Kong/deck#144]
We have a custom plugin where the configuration is an array - the JSON looks like this:
```json
{
  "headers": [
    {
      "name": "X-Foo",
      "rules": [
        {
          "value": "0",
          "upstream": "foo.com"
        },
        {
          "value": "1",
          "upstream": "bar.com"
        }
      ]
    }
  ]
}
```
cURL:
```shell
curl -i -X POST \
  --url http://localhost:8001/routes/some-service/plugins \
  --header 'content-type: application/json' \
  --data '{"name": "foo-plugin", "config": {"headers":[{"name":"X-Foo","rules":[{"value":"0","upstream":"foo.com"},{"value":"1","upstream":"bar.com"}]}]}}'
```
`deck` dumps the plugin entry like so:
```yaml
- name: foo-plugin
  config:
    headers:
    - name: X-Foo
      rules:
      - upstream: foo.com
        value: "0"
      - upstream: bar.com
        value: "1"
  enabled: true
  protocols:
  - grpc
  - grpcs
  - http
  - https
```
That appears to be a valid YAML array, but when performing a `deck sync` it seems that `deck` is omitting the `headers` array entirely when sending it:
```shell
while processing event: {Update} failed: 400 Bad Request {"message":"schema violation (config.headers: required field missing)","name":"schema violation","fields":{"config":{"headers":"required field missing"}},"code":2}
```
Other than that `deck` has been working wonderfully - thanks for such a great tool!
