### ISSUE TITLE
custom-entities do not support `deck gateway apply`

### ISSUE THREAD

**Issue by mheap** [Kong/deck#1568]
When referencing foreign keys in `custom_entities`, deck does not prebuild the state as expected.

## Reproduction

```
echo '_format_version: "3.0"
custom_entities:
- fields:
    methods:
    - GET
    query: query { viewer { login } }
    service:
      name: example
    uri: /me
  id: ec3c97ee-e77b-481c-b09b-fb49d1a1be78
  type: degraphql_routes
services:
- connect_timeout: 60000
  enabled: true
  host: example.com
  name: example
  plugins:
  - config:
      graphql_server_path: /graphql
    enabled: true
    name: degraphql
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  tags:
    - foo' | deck gateway sync

Now try updating the custom entity only using `apply`:

```yaml
echo '_format_version: "3.0"
custom_entities:
- fields:
    methods:
    - GET
    query: query { viewer { login } }
    service:
      name: example
    uri: /me
  id: ec3c97ee-e77b-481c-b09b-fb49d1a1be78
  type: degraphql_routes` | deck file apply
```

It works as expected if you specify `default_lookup_tags`. Lookup tags should automatically be added if running `apply`:

```yaml
echo '_format_version: "3.0"
_info:
  default_lookup_tags:
    services:
      - foo
custom_entities:
- fields:
    methods:
    - GET
    query: query { viewer { login } }
    service:
      name: example
    uri: /me
  id: ec3c97ee-e77b-481c-b09b-fb49d1a1be78
  type: degraphql_routes` | deck file apply
```

See https://github.com/Kong/go-database-reconciler/blob/7001878f685ab8ea9ea865c1b7d0e96fecd28499/pkg/file/builder.go#L1002-L1017
