### ISSUE TITLE
Inconsistencies in foreign key reference format in deck

### ISSUE THREAD

**Issue by Prashansa-K** [Kong/deck#1594]
In routes, we use a dict to refer to a service (notice  service: {name: svc1} )
```
services:
- host: mockbin.org
  name: svc1
routes:
- name: foo
  paths:
  - /foo
  service:
    name: svc1
```

Same convention is followed for degraphql_routes.

However, plugins expect a string value, rather than a dict. The API accepts a dict (as checked with GW 3.8) but deck format doesn't.
