### ISSUE TITLE
Partials: No error when partial can't be found

### ISSUE THREAD

**Issue by mheap** [Kong/deck#1649]
Define partials on a plugin but without defining the partials itself.  The configuration syncs but no references to partials.  I would expect some error instead.

```
$ deck version
decK v1.47.1 (5095f80) 
```

```
$ deck gateway ping
Successfully connected to Kong!
Kong version:  3.10.0.2
```

Steps to Reproduce:

1. Do a deck reset to clean any config

```
$ deck gateway reset -f
Summary:
  Created: 0
  Updated: 0
  Deleted: 0
```

2. Define this Service Route Plugin with a partials in a deck file.  Added an  attachment as  my-kong-config.yaml:

```
_format_version: "3.0"
services:
- host: httpbin.konghq.com
  name: httpbin
  path: /anything
  plugins:
  - config:
      identifier: ip
      limit:
      - 10000
      namespace: testns
      strategy: redis
      sync_rate: 2
      window_size:
      - 30
      window_type: sliding
    name: rate-limiting-advanced
    partials:
    - id: a426adc7-7f11-4cda-a862-112ddabae9ef
      name: redis-common-1
      path: config.redis
  port: 443
  protocol: https
  routes:
  - name: anything
    paths:
    - /anything
```

3. Do a deck sync of above config no errors

```
$ deck gateway sync my-kong-config.yaml 
creating service httpbin
creating route anything
creating plugin rate-limiting-advanced for service httpbin
Summary:
  Created: 3
  Updated: 0
  Deleted: 0
```

4. Do a deck dump the plugin's partial config is gone:

```
$ deck gateway dump
_format_version: "3.0"
services:
- connect_timeout: 60000
  enabled: true
  host: httpbin.konghq.com
  name: httpbin
  path: /anything
  plugins:
  - config:
      compound_identifier: null
      consumer_groups: null
      dictionary_name: kong_rate_limiting_counters
      disable_penalty: false
      enforce_consumer_groups: false
      error_code: 429
      error_message: API rate limit exceeded
      header_name: null
      hide_client_headers: false
      identifier: ip
      limit:
      - 10000
      lock_dictionary_name: kong_locks
      namespace: testns
      path: null
      redis:
        cluster_addresses: null
        cluster_max_redirections: 5
        cluster_nodes: null
        connect_timeout: 2000
        connection_is_proxied: false
        database: 0
        host: 127.0.0.1
        keepalive_backlog: null
        keepalive_pool_size: 256
        password: null
        port: 6379
        read_timeout: 2000
        redis_proxy_type: null
        send_timeout: 2000
        sentinel_addresses: null
        sentinel_master: null
        sentinel_nodes: null
        sentinel_password: null
        sentinel_role: null
        sentinel_username: null
        server_name: null
        ssl: false
        ssl_verify: false
        timeout: 2000
        username: null
      retry_after_jitter_max: 0
      strategy: redis
      sync_rate: 2
      window_size:
      - 30
      window_type: sliding
    enabled: true
    name: rate-limiting-advanced
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: anything
    path_handling: v0
    paths:
    - /anything
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
```
