### ISSUE TITLE
Partials: Configuring Partials with tags

### ISSUE THREAD

**Issue by mheap** [Kong/deck#1650]
User would like team A to configure the redis partials for all the other teams B and C. 

So creates a partials like:

```
_format_version: "3.0"
partials:
- id: b426adc7-7f11-4cda-a862-112ddabae9ef
  name: redis-common
  tags:
  - redis-common
  type: redis-ee
  config:
    sentinel_master: mymaster
    sentinel_nodes:
     - host: redis-node-0
       port: 26379
     - host: redis-node-1
       port: 26379
     - host: redis-node-2
       port: 26379
    sentinel_role: master
```

It syncs the partials.yaml:
```
$ deck gateway sync partials.yaml --select-tag "redis-common"
creating partial redis-common
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
```

Then creates a Service Route Plugin with different tag that team B manages:

```
_format_version: "3.0"
services:
- host: httpbin.konghq.com
  name: httpbin-1
  path: /anything
  tags: ["api:partials-test-1"]
  plugins:
  - config:
      identifier: ip
      limit:
      - 10000
      namespace: testns
      strategy: redis
      sync_rate: 2
      window_size:
      - 30
      window_type: sliding
    name: rate-limiting-advanced
    tags: ["api:partials-test-1"]
    partials:
    - id: b426adc7-7f11-4cda-a862-112ddabae9ef
      name: redis-common
      path: config.redis
  port: 443
  protocol: https
  routes:
  - name: anything-1
    tags: ["api:partials-test-1"]
    paths:
    - /anything1
```

It syncs:

```
$ deck gateway sync service-1.yaml --select-tag "api:partials-test-1"
creating service httpbin-1
creating route anything-1
creating plugin rate-limiting-advanced for service httpbin-1
Summary:
  Created: 3
  Updated: 0
  Deleted: 0
```

But the Partial in the plugin  is not applied:

```
$ deck gateway dump
_format_version: "3.0"
partials:
- config:
    cluster_max_redirections: 5
    cluster_nodes: null
    connect_timeout: 2000
    connection_is_proxied: false
    database: 0
    host: 127.0.0.1
    keepalive_backlog: null
    keepalive_pool_size: 256
    password: null
    port: 6379
    read_timeout: 2000
    send_timeout: 2000
    sentinel_master: mymaster
    sentinel_nodes:
    - host: redis-node-0
      port: 26379
    - host: redis-node-1
      port: 26379
    - host: redis-node-2
      port: 26379
    sentinel_password: null
    sentinel_role: master
    sentinel_username: null
    server_name: null
    ssl: false
    ssl_verify: false
    username: null
  id: b426adc7-7f11-4cda-a862-112ddabae9ef
  name: redis-common
  tags:
  - redis-common
  type: redis-ee
services:
- connect_timeout: 60000
  enabled: true
  host: httpbin.konghq.com
  name: httpbin-1
  path: /anything
  plugins:
  - config:
      compound_identifier: null
      consumer_groups: null
      dictionary_name: kong_rate_limiting_counters
      disable_penalty: false
      enforce_consumer_groups: false
      error_code: 429
      error_message: API rate limit exceeded
      header_name: null
      hide_client_headers: false
      identifier: ip
      limit:
      - 10000
      lock_dictionary_name: kong_locks
      namespace: testns
      path: null
      redis:
        cluster_addresses: null
        cluster_max_redirections: 5
        cluster_nodes: null
        connect_timeout: 2000
        connection_is_proxied: false
        database: 0
        host: 127.0.0.1
        keepalive_backlog: null
        keepalive_pool_size: 256
        password: null
        port: 6379
        read_timeout: 2000
        redis_proxy_type: null
        send_timeout: 2000
        sentinel_addresses: null
        sentinel_master: null
        sentinel_nodes: null
        sentinel_password: null
        sentinel_role: null
        sentinel_username: null
        server_name: null
        ssl: false
        ssl_verify: false
        timeout: 2000
        username: null
      retry_after_jitter_max: 0
      strategy: redis
      sync_rate: 2
      window_size:
      - 30
      window_type: sliding
    enabled: true
    name: rate-limiting-advanced
    protocols:
    - grpc
    - grpcs
    - http
    - https
    tags:
    - api:partials-test-1
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: anything-1
    path_handling: v0
    paths:
    - /anything1
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
    tags:
    - api:partials-test-1
  tags:
  - api:partials-test-1
  write_timeout: 60000
```

To apply the partial team B must provide both files, but I don't think this is correct.

```
$ deck gateway sync partials.yaml service-1.yaml --select-tag "api:partials-test-1"
```

Team C tried also to use default_lookup_tags as suggested in the docs: https://docs.konghq.com/deck/gateway/tags/#main 

```
_format_version: "3.0"
_info:
  default_lookup_tags:
    partials:
     - redis-common
services:
- host: httpbin.konghq.com
  name: httpbin-2
  (....)
```

but not working

```
$ deck gateway sync service-2.yaml --select-tag "api:partials-test-2"
Error: 1 errors occurred:
	reading file service-2.yaml: validating file content: 1 errors occurred:
	validation error: object=["redis-common"], err=_info.default_lookup_tags: Additional property partials is not allowed
```

How should be partials work with tags?  I would expect the same behavior than consumers and consumer-groups.
