### ISSUE TITLE
Route not selected when tag is included in deck gateway dump command

### ISSUE THREAD

**Issue by realAndroid** [Kong/deck#1672]
I created a route under one of my services.
I want to dump the config of my route. My route has a single tag `alaintest`. When I run:

`deck gateway dump --konnect-control-plane-name="myCP" --konnect-token="myToken" --select-tag "alaintest"`

I get an almost empty result:

```
_format_version: "3.0"
_info:
  defaults: {}
  select_tags:
  - alaintest
_konnect:
  control_plane_name: myCP
```

The command works for other tags like service tags, but not for route tags.
[The documentation says](https://developer.konghq.com/deck/gateway/tags/): "Default lookup tags can be used on Services, **Routes**, Consumers and Consumer Groups."

However, I noticed deck dump does not work when I want to select routes only. Any ideas?

Thank you!
