### ISSUE TITLE
in '_plugin_configs': unknown field

### ISSUE THREAD

**Issue by matteodisabatino** [Kong/deck#209]
Hi, I'm using Kong 2 via Docker, my purpose is de-duplicate a plugin configuration (as the [official documentation](https://docs.konghq.com/deck/guides/deduplicate-plugin-configuration/) says).

First I tried this declarative configuration:

```yml
_format_version: "2.1"

services:
- host: rest-service
  name: rest-service
  port: 80
  protocol: http
  routes:
  - name: root
    paths:
    - /
    preserve_host: false
    strip_path: true
    plugins:
    - name: kong-external-auth
      config: 
        url: http://auth-service
        path: /
  - name: public-route
    paths:
    - /public-route
    preserve_host: false
    strip_path: false
```

And then I tried this one:

```yml
_format_version: "2.1"

_plugin_configs:
  my-auth-service:
    url: http://auth-service
    path: /

services:
- host: rest-service
  name: rest-service
  port: 80
  protocol: http
  routes:
  - name: root
    paths:
    - /
    preserve_host: false
    strip_path: true
    plugins:
    - name: kong-external-auth
      _config: my-auth-service
  - name: public-route
    paths:
    - /public-route
    preserve_host: false
    strip_path: false
```

The problem is that the first configuration successfully works, the second one not. In the second case I receive this error:

```
2020/09/07 19:03:05 [warn] 1#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:60
nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:60
2020/09/07 19:03:05 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:491: error parsing declarative config file /usr/local/kong/declarative/kong.yml:
in 'services':
  - in entry 1 of 'services':
    in 'routes':
      - in entry 1 of 'routes':
        in 'plugins':
          - in entry 1 of 'plugins':
            in 'config':
              in 'url': required field missing
              in 'path': required field missing
            in '_config': unknown field
in '_plugin_configs': unknown field
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:491: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:491: error parsing declarative config file /usr/local/kong/declarative/kong.yml:
in 'services':
  - in entry 1 of 'services':
    in 'routes':
      - in entry 1 of 'routes':
        in 'plugins':
          - in entry 1 of 'plugins':
            in 'config':
              in 'url': required field missing
              in 'path': required field missing
            in '_config': unknown field
in '_plugin_configs': unknown field
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:491: in function 'init'
	init_by_lua:3: in main chunk
```

In particular I cannot understand why the error says `'_config': unknown field` and `'_plugin_configs': unknown field` since these are the fields used in the official documentation. What am I wronging?
