### ISSUE TITLE
deck dump with --select-tag problem

### ISSUE THREAD

**Issue by dynastini1** [Kong/deck#212]
After creating service 'test':
```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test

services:
- name: test
  url: http://localhost:1111
  retries: 5
```
and adding route to it with 'test2' tag:
```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test2

routes:
- name: test2
  service:
    name: test
  paths:
  - "/test2"
  path_handling: v0
  https_redirect_status_code: 426
```
```deck dump --select-tag test2``` didn't see that route:
```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test2
```

**Comment by hbagdi** [comment]
A service and all of it's routes need to be in the same state file, meaning, they should use the same `select-tags`.

Would the following work for you?


```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test
services:
- name: test
  url: http://localhost:1111
  retries: 5
routes:
- name: test2
  service: test
  paths:
  - "/test2"
  path_handling: v0
  https_redirect_status_code: 426
```
