### ISSUE TITLE
'deck diff' show difference for service.name

### ISSUE THREAD

**Issue by dynastini1** [Kong/deck#213]
When using such configuration:
```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test

routes:
- name: test
  service:
    name: test
  paths:
  - "/test1"
  path_handling: v0
  https_redirect_status_code: 426
```

```deck diff -s test.yaml``` can't handle 'service.name' in 'routes' configuration and showing difference:
```diff
updating route test1  {
-  "created_at": 1.600672019e+09,
   "https_redirect_status_code": 426,
   "id": "d876c109-8ed2-48b5-9cb5-31b7379ab985",
   "name": "test1",
   "path_handling": "v0",
   "paths": [
     "/test1"
   ],
   "preserve_host": false,
   "protocols": [
     "http",
     "https"
   ],
   "regex_priority": 0,
   "service": {
-    "id": "9af11672-7781-4af2-b8e7-383d435a2bf1"
+    "name": "test"
   },
   "strip_path": false,
   "tags": [
     "test"
   ],
-  "updated_at": 1.600672019e+09
 }
```

**Comment by hbagdi** [comment]
That is against the spec of kong's declarative configuration.

Please instead use:

```yaml
_format_version: "1.1"
_info:
  select_tags:
  - test

routes:
- name: test
  service: test
  paths:
  - "/test1"
  path_handling: v0
  https_redirect_status_code: 426
```

And please ensure that `test` service is defined as well.
