### ISSUE TITLE
How to DRY configuration when you have multiple clusters

### ISSUE THREAD

**Issue by grebois** [Kong/deck#214]
Hi @hbagdi,

I got a question regarding how to DRY configuration when you have multiple clusters with similar services.

So the problems I am trying to solve are:

1) How to declaratively specify which resources are/need to be sync with a specific cluster

2) How to be able to modify some variables, as the resource might not be exactly the same for all cluster.

So, lets say you have 2 clusters, `kong-0.dev.us-west-2` and `kong-1.dev.us-west-2`, and most of the configuration between this clusters is shared but some services/routes are different, the most simple example I can think of is, 2 services defined in separate files, `test-backend.kong.https.svc.yaml` and `test-frontend.kong.https.svc.yaml`, and I would like to configure the first cluster `kong-0.dev.us-west-2` with both services, BUT the second one `kong-1.dev.us-west-2` only with the frontend, `test-frontend.kong.https.svc.yaml`.

Ideally I would like to have a file `kong-0.dev.us-west-2.yaml` defining the resources of that kong and another file for `kong-1.dev.us-west-2`,

`kong-0.dev.us-west-2.yaml`

```
resources:
  - test-frontend.kong.https.svc
  - test-backend.kong.https.svc
```

And then

`kong-1.dev.us-west-2.yaml`

```
resources:
  - test-frontend.kong.https.svc
```

But the other problem is that the routes for this 2 clusters are going to be different;

`test-frontend.kong.https.svc.yaml` for `kong-0.dev.us-west-2` is

```
_format_version: "1.1"
services:
  - host: test-frontend.kong.https.svc
...
    routes:
      - hosts:
          - '*.test.dev.us-west-2'
...
```

Then `test-frontend.kong.https.svc.yaml` for `kong-1.dev.us-west-2` should be 

```
_format_version: "1.1"
services:
  - host: test-backend.kong.https.svc
...
    routes:
      - hosts:
          - '*.test.dev-1.us-west-2'
...
```

So ideally what I am after is something like:

`test-frontend.kong.https.svc.yaml`

```
_format_version: "1.1"
services:
  - host: test-frontend.kong.https.svc
...
    routes:
      - hosts:
          - '*.test.{{ var.env }}.us-west-2'
...
```

And then 

`kong-1.dev.us-west-2.yaml`

```
resources:
  - gambit-backend.kong.https.svc
variables:
  - env: dev1
```

I've tried using https://github.com/k14s/ytt and https://github.com/fluxcd/toolkit but they don't really solve this.  

Another thought is to use tag, but, lets say I have my resources tagged after a `dump` with:

```
_info:
  select_tags:
  - kong-0.dev.us-west-2
```

then when I want to sync this resources with a new test cluster `kong-3.dev.us-west-2`;

```
deck sync --select-tag kong-0.dev.us-west-2 
```

it will always try to create all the resources, also tagging them with `kong-0.dev.us-west-2` even when I do:

```
deck sync --select-tag kong-1.dev.us-west-2 
```

or

```
deck sync
```

I guess another possible solution would be that the `diff` and `sync` commands filter the tags as `dump` do, but still this doesn't solve any of the first 2 problems.

What do you think?

**Comment by hbagdi** [comment]
1. For the configuration that is shared between the two clusters, create a file `common.yaml`.
2. Create cluster-specific files like `cluster1.yaml` and `cluster2.yaml`.
3. You can choose to use select-tags or avoid, that depends on other use case you have.

Now, to sync to cluster 1:
```
deck sync --state common.yaml --state cluster1.yaml
```

Now, to sync to cluster 2:
```
deck sync --state common.yaml --state cluster2.yaml
```

To further deduplicate YAML, try solutions like jinja2 to template YAML.

**Comment by grebois** [comment]
Would it make sense to be able to filter by resource? something like;

```
deck sync --state common.yaml --resource test-frontend.kong.https.svc
```

This could also work like:

```
deck sync --resource test-frontend.kong.https.svc
```

**Comment by hbagdi** [comment]
My current thinking is that would add a lot more complexity for little gains.

Have you tried defining `test-frontend.kong.https.svc` resource in a YAML file and then syncing only that specific resource?

**Comment by grebois** [comment]
yes, and it deletes all others

**Comment by hbagdi** [comment]
Are you using a unique select-tag for that specific resource? That will prevent from the problem at hand.

**Comment by grebois** [comment]
now it gets more weird;

I go to the manager and tag the service and routes with `test-frontend.kong.https.svc`, then I go to the console:

```
❯ deck dump --select-tag test-frontend.kong.https.svc
cat kong.yaml
_format_version: "1.1"
_info:
  select_tags:
  - test-frontend.kong.https.svc
services:
- connect_timeout: 60000
  host: test-frontend.kong.https.svc
  name: kong.test-frontend.https
  path: /
  port: 80
  protocol: https
  read_timeout: 600000
  retries: 5
  write_timeout: 600000

```

but when I do, `deck dump` the same resource looks like this:

```
_format_version: "1.1"
services:
  - connect_timeout: 60000
    host: test-frontend.kong.https.svc
    name: kong.test-frontend.https
    path: /
    port: 80
    protocol: https
    read_timeout: 600000
    retries: 5
    write_timeout: 600000
    tags:
      - test-frontend.kong.https.svc
    routes:
      - hosts:
          - '*.test.dev.us-west-2'
        name: kong.test-frontend-admin.00
        paths:
          - /
        path_handling: v1
        preserve_host: true
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: false
        tags:
          - test-frontend.kong.https.svc
        https_redirect_status_code: 426
      - hosts:
          - go.test.dev.us-west-2
        name: kong.test-frontend-webex.00
        paths:
          - /
        path_handling: v1
        preserve_host: true
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: false
        tags:
          - test-frontend.kong.https.svc
        https_redirect_status_code: 426
```

furthermore:

```
❯ deck diff --state test-frontend.kong.https.svc.yaml
Summary:
  Created: 0
  Updated: 0
  Deleted: 0

❯ deck diff --state kong.yaml
deleting route kong.test-frontend-admin.00
deleting route kong.test-frontend-webex.00
Summary:
  Created: 0
  Updated: 0
  Deleted: 2

❯ deck diff --state kong.yaml --select-tag test-frontend.kong.https.svc
deleting route kong.test-frontend-admin.00
deleting route kong.test-frontend-webex.00
Summary:
  Created: 0
  Updated: 0
  Deleted: 2

```

now manually adding `select_tags` to `test-frontend.kong.https.svc.yaml`

```
_format_version: "1.1"
_info:
  select_tags:
  - test-frontend.kong.https.svc
```

results in:

```
❯ deck diff --state test-frontend.kong.https.svc.yaml
Summary:
  Created: 0
  Updated: 0
  Deleted: 0

❯ deck diff --state kong.yaml
deleting route kong.test-frontend-webex.00
deleting route kong.test-frontend-admin.00
Summary:
  Created: 0
  Updated: 0
  Deleted: 2

❯ deck diff --state kong.yaml --select-tag test-frontend.kong.https.svc
deleting route kong.test-frontend-webex.00
deleting route kong.test-frontend-admin.00
Summary:
  Created: 0
  Updated: 0
  Deleted: 2
```
