### ISSUE TITLE
Ability to reference a certificate/ca_certificate generated within a different select-tag

### ISSUE THREAD

**Issue by ikethecoder** [Kong/deck#268]
We have a use case where we have a separate team that manages client certificates from the team that manages the service/routes.  Deck currently does not allow a certificate generated using one select-tag scope, to be used by a service in another select-tag scope.  For example:

### STEP 1:
**client_certs.yaml**
```
certificates:
- cert: "<PEM>"
  key: "<PEM>"
  tags: [ ns.certmgmt ]
  id: 18cee516-6268-11eb-ae93-0242ac130012
```
`deck sync --select-tag ns.certmgmt --state client_certs.yaml`

### STEP 2:
**services.yaml**
```
services:
- name: my-mtls-upstream
  host: my-tls-upstream.site
  tags: [ ns.productX ]
  port: 443
  protocol: https
  client_certificate: 18cee516-6268-11eb-ae93-0242ac130012
```
`deck sync --select-tag ns.productX --state services.yaml`

**Observed behaviour:** 
* When running step 2, `deck` returns an error `client certificate not found: 18cee516-6268-11eb-ae93-0242ac130012`.

**Desired behaviour:**
* Deck allows the sync to occur in step 2.
