### ISSUE TITLE
feature: exclusion/inclusion of plugins via additional metadata on services/routes

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#339]
Users have expressed a need for two things:
- Ability to apply a global plugin but exclude certain services/routes (https://github.com/Kong/kong/issues/5233)
- Ability to define plugins templates and then directly use them on services/routes

The scope here is to figure out a way to define these things using decK's state file and then decK does the heavy lifting in the background to render the correct state and sync it to Kong.

**Comment by zekth** [comment]
What about having something like:
```yaml
---
_format_version: "3.0"
_info:
  defaults:
    service:
      plugins:
      - name: foo
      _exclude_tag: bar
```
So this would add the plugin `foo` to all services without the tag `bar`. We can also do the other way with `_include_tag`.
On the same note i'd expect when a service has already the plugin `foo` to have its own definition overriding the `defaults` one.

What do you think @hbagdi ? i can work on this.
