### ISSUE TITLE
tags specified with `--select-tag` are not added

### ISSUE THREAD

**Issue by Tieske** [Kong/deck#362]
when running a `deck sync` the tags used to select the entities from the Kong datastore, should also be added to the entities being added to Kong, but this doesn't happen.

So after a first sync;
```shell
deck sync --select-tag=tieske -s xxx.yaml
```
returns this summary (on a blank datastore):
```
Summary:
  Created: 44
  Updated: 0
  Deleted: 0
```
everything is added, but without a tag `tieske`.

The following command;
```shell
deck diff --select-tag=tieske -s xxx.yaml
```
should return a summary of doing nothing, but it actually returns;
```
Summary:
  Created: 44
  Updated: 0
  Deleted: 0
```
The cause being that the tag was not added, hence the 2nd command selects nothing and adds everything again.
