### ISSUE TITLE
deck sync results in a panic if all entities exist

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#396]
state file:
```yaml
_format_version: "1.1"
services:
- connect_timeout: 60000
  host: httpbin.org
  name: svc1
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 301
    name: r1
    path_handling: v0
    paths:
    - /r1
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - managed-by-deck
    - org-unit-42
  tags:
  - team-svc1
  - managed-by-deck
  - org-unit-42
  write_timeout: 60000
```

Steps to reproduce:
```shell
➜  deck git:(main) ✗ go run main.go sync  --kong-addr http://localhost:7001 --headers 'kong-admin-token:CHANGE_ME'                                                                                                 
creating service svc1                                                                                    
creating route r1                                                                                                                                                                                                  
Summary:                                                                                                 
  Created: 2                                        
  Updated: 0                                                                                                                                                                                                       
  Deleted: 0                                                                                             
➜  deck git:(main) ✗ go run main.go sync  --kong-addr http://localhost:7001 --headers 'kong-admin-token:CHANGE_ME'                                                                                                 
panic: interface conversion: interface {} is *state.Service, not *state.Document                                                                                                                                   
                                                                                                                                                                                                                   
goroutine 135 [running]:                                                                                                                                                                                           
github.com/kong/deck/solver.Solve.func2(0xa3684f, 0x6, 0xa37255, 0x7, 0x9f8f20, 0xc00027b380, 0x9f8f20, 0xc00027b440, 0x1fa6ff510040d1aa, 0x60a6a301, ...)                                                         
        /home/hbagdi/deck/solver/solver.go:53 +0xb7f                                   
github.com/kong/deck/diff.(*Syncer).handleEvent.func1(0xc000697960, 0xc000697960)                                                                                                                                  
        /home/hbagdi/deck/diff/diff.go:472 +0xaf                                                         
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc000274e28, 0xaee688, 0xc000697960, 0x0, 0xaf1c30, 0xc000232230, 0x0, 0x0)                                                                                   
        /home/hbagdi/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 +0x102                 
github.com/cenkalti/backoff/v4.RetryNotify(...)                                                          
        /home/hbagdi/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34                        
github.com/cenkalti/backoff/v4.Retry(...)                                                                
        /home/hbagdi/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:28                        
github.com/kong/deck/diff.(*Syncer).handleEvent(0xc00023f040, 0xc000697740, 0xa3684f, 0x6, 0xa37255, 0x7, 0x9f8f20, 0xc00027b380, 0x9f8f20, 0xc00027b440, ...)                                                     
        /home/hbagdi/deck/diff/diff.go:471 +0xfa                                                         
github.com/kong/deck/diff.(*Syncer).eventLoop(0xc00023f040, 0xc000697740, 0x0, 0x0)                      
        /home/hbagdi/deck/diff/diff.go:461 +0x165                                                                                                                                                                  
github.com/kong/deck/diff.(*Syncer).Run.func1(0xc00023f040, 0xc000697740, 0xc000528330)
        /home/hbagdi/deck/diff/diff.go:398 +0x39    
created by github.com/kong/deck/diff.(*Syncer).Run                                                                                                                                                                 
        /home/hbagdi/deck/diff/diff.go:397 +0x185                                                        
```
