### ISSUE TITLE
Recieve "while post processing event: entity not found" error when updating tag set

### ISSUE THREAD

**Issue by rasmusoh** [Kong/deck#467]
**Kong version: Enterprise 2.4**

### Description:
When I try to do deck sync against my workspace, after adding or removing a tag to a upstream target, I receive the error:

```
Error: 1 errors occurred:
        while post processing event: entity not found
```

Running deck sync a second time with the same yaml resolves the issue, no errors and everything is updated.

Just adding and removing to the tags list of the very basic example below was enough to replicate the issue.
```
_format_version: "1.1"
_workspace: my_workspace
upstreams:
- algorithm: round-robin
  hash_fallback: none
  hash_on: none
  hash_on_cookie_path: /
  name: my_upstream
  slots: 10000
  targets:
  - tags:
      - tag1
    target: localhost:1234
    weight: 100
```
