### ISSUE TITLE
Deck docker config issue

### ISSUE THREAD

**Issue by klorant5** [Kong/deck#505]
Hi. I am new to kong and deck and I would like to configure deck with Docker but I can't find a good resource which would help me in that. 

Here is my docker-compose file:
```
version: '3.9'
services:
    kong-db:
      image: postgres:9.6-alpine
      restart: always
      hostname: kong-database
      container_name: kong-database
      environment:
        POSTGRES_USER: ${KONG_DB_USERNAME}
        POSTGRES_DB: ${KONG_DB_NAME}
        POSTGRES_PASSWORD: ${KONG_DB_PASSWORD}
      ports:
        - "5432:5432"

    kong-bootstrap:
      image: kong:2.6.0-alpine
      restart: 'on-failure'
      hostname: kong-bootstrap
      container_name: kong-bootstrap
      depends_on:
        - kong-db
      environment:
        KONG_DATABASE: ${KONG_DATABASE}
        KONG_PG_HOST: ${KONG_DB_HOST}
        KONG_PG_DATABASE: ${KONG_DB_NAME}
        KONG_PG_USER: ${KONG_DB_USERNAME}
        KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      command: "kong migrations bootstrap"

    kong:
      image: kong:2.6.0-alpine
      restart: always
      hostname: kong
      container_name: kong
      depends_on:
        - kong-bootstrap
      environment:
        KONG_DATABASE: ${KONG_DATABASE}
        KONG_PG_HOST: ${KONG_DB_HOST}
        KONG_PG_DATABASE: ${KONG_DB_NAME}
        KONG_PG_USER: ${KONG_DB_USERNAME}
        KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
        KONG_PROXY_ACCESS_LOG: ${KONG_PROXY_ACCESS_LOG}
        KONG_ADMIN_ACCESS_LOG: ${KONG_ADMIN_ACCESS_LOG}
        KONG_PROXY_ERROR_LOG: ${KONG_PROXY_ERROR_LOG}
        KONG_ADMIN_ERROR_LOG: ${KONG_ADMIN_ERROR_LOG}
        KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN}
      command: "kong start"
      ports:
        - $KONG_PROXY_PORT:8000
        - $KONG_PROXY_SSL_PORT:8443
        - $KONG_PROXY_ADMIN_API_PORT:8001
        - $KONG_PROXY_ADMIN_SSL_API_PORT:8444
networks:
  default:
    name: kong-net
```

I tried to run the kong/deck docker image alone without docker-compose but it didn't start. It got downloaded but not started.
Did I miss a config option? In the documentation of deck there is a volume mentioned but I don't know how should I create it.

My main goal would be to have a directory in my project with configs of kong exported with deck and when I run docker-compose up then all the necessary containers would be created, the bootstrap process would run and after that all the configs would be imported from the previously mentioned directory with deck.
Can anybody help me with this?
