### ISSUE TITLE
Additional property _transform is not allowed

### ISSUE THREAD

**Issue by black-snow** [Kong/deck#511]
I'm just starting with kong and I pulled a `kong.yaml` from [the docs](https://docs.konghq.com/gateway-oss/2.6.x/db-less-and-declarative-config/#the-declarative-configuration-format) that should be fine:

```yaml
_format_version: "2.1"
_transform: true

services:
- name: my-service
  url: https://example.com
  plugins:
  - name: key-auth
  routes:
  - name: my-route
    paths:
    - /

consumers:
- username: my-user
  keyauth_credentials:
  - key: my-key
```

But when I `deck validate` this thing I end up with:

```
Error: reading file: validating file content: 1 errors occurred:
        (root): Additional property _transform is not allowed

```

Shouldn't the declarative docs match what deck is capable of? Or is there some other issue?

`decK v1.8.2 (b538f70)`

---

P.S.: I also stumbled upon `Error: reading state file: stat kong.yaml: no such file or directory` because I named it `kong.yml` instead ... I'd open a PR to allow both if my go skill weren't about `-1`. ;)
