### ISSUE TITLE
deck diff shows different plugin configuration than sync creates

### ISSUE THREAD

**Issue by odsock** [Kong/deck#538]
Using decK v1.8.2 (b538f70). 
When updating a request-transformer plugin configuration to change list of headers to remove, the diff output is incorrect. I'm changing the config from removing one header, to removing two different headers. Syncing the change has the correct result, only the diff output is wrong (output in both diff and sync).

Original state yaml:
```
      remove:
        body: []
        headers:
        - x-posting-ip
        querystring: []
```

The change:
```
      remove:
        body: []
        headers:
        - accept-encoding
        - x-forwarded-for
        querystring: []
```

The diff output shows the original single entry being removed, and then the first of the two new entries twice:
```
       "headers": [
-        "x-posting-ip"
+        "accept-encoding"
+        "accept-encoding"
       ],
```

It should be this:
```
       "headers": [
-        "x-posting-ip"
+        "accept-encoding"
+        "x-forwarded-for"
       ],
```

Example configuration and output attached.
[deck-test.zip](https://github.com/Kong/deck/files/7653203/deck-test.zip)
