### ISSUE TITLE
DecK is showing a difference when specifying multiple state files

### ISSUE THREAD

**Issue by meesvandongen** [Kong/deck#574]
Let's say I have 2 files, which specify distributed config:
```yaml
_format_version: "1.1"
_info:
  select_tags:
  - tag_a
services:
  - ....
```

```yaml
_format_version: "1.1"
_info:
  select_tags:
  - tag_b
services:
  - ....
```

Then, doing
```sh
deck diff -s a.yaml -s b.yaml
```
Will result in a diff, even though diffing these files individually shows no diff.

I would expect there to be no diff in both cases.

Is this just a limitation of distributed configuration, and am I better off calling deck diff a bunch of times, once for each file?
