### ISSUE TITLE
Invalid data type in deck dump --rbac-resources-only and unique violation in sync

### ISSUE THREAD

**Issue by pmutyala** [Kong/deck#586]
Hello

We have a kong gw enterprise and using decK v1.10.0 (27094f2) to dump rbac resources, and notice the output has wrong data type causing sync to fail with invalid data type error

``` bash
deck sync --headers "kong-admin-token: {{rbac}}" --kong-addr http://kube-kong-admin.intradsm1 -s default.yaml
Error: reading file: validating file content: 8 errors occurred:
	rbac_roles.0.endpoint_permissions.0.actions: Invalid type. Expected: array, given: string
	rbac_roles.1.endpoint_permissions.0.actions: Invalid type. Expected: array, given: string
	rbac_roles.1.endpoint_permissions.1.actions: Invalid type. Expected: array, given: string
	rbac_roles.1.endpoint_permissions.2.actions: Invalid type. Expected: array, given: string
	rbac_roles.1.endpoint_permissions.3.actions: Invalid type. Expected: array, given: string
	rbac_roles.1.endpoint_permissions.4.actions: Invalid type. Expected: array, given: string
	rbac_roles.1.endpoint_permissions.5.actions: Invalid type. Expected: array, given: string
	rbac_roles.2.endpoint_permissions.0.actions: Invalid type. Expected: array, given: string

```

If i correct the actions to be from below 
```yaml
rbac_roles:
- comment: Full access to all endpoints, across all workspaces
  endpoint_permissions:
  - actions: delete,create,read,update
 ```
to 
```yaml 
rbac_roles:
- comment: Full access to all endpoints, across all workspaces
  endpoint_permissions:
  - actions: 
    - delete,
    - create,
    - update
 ```

sync works, but i get unique violation

```bash
 deck sync --headers "kong-admin-token: {{token}}" --kong-addr http://kube-kong-admin.service.intraiad1.com -s kong.yaml
creating rbac-role admin
creating rbac-role read-only
creating rbac-role super-admin
Summary:
  Created: 0
  Updated: 0
  Deleted: 0
Error: 3 errors occurred:
	while processing event: {Create} rbac-role read-only failed: HTTP status 409 (message: "UNIQUE violation detected on '{name=\"read-only\"}'")
	while processing event: {Create} rbac-role admin failed: HTTP status 409 (message: "UNIQUE violation detected on '{name=\"admin\"}'")
	while processing event: {Create} rbac-role super-admin failed: HTTP status 409 (message: "UNIQUE violation detected on '{name=\"super-admin\"}'")

```

are these known issues ?
