### ISSUE TITLE
De-duplicate plugin configuration incompatible with validate --online

### ISSUE THREAD

**Issue by dschniepp** [Kong/deck#593]
Thank you for the great addition of `deck validate --online` which came with release **v1.11.0**. 

As far as I can see the two features **validate online** and **de-duplicate plugin configuration** are incompatible.

I used the following config to isolate the issue

```yaml
_format_version: "2.1"

_plugin_configs:
  rate-limiting-one:
    minute: 6000
    policy: local
    hide_client_headers: true
  
services:
- name: sample
  url: https://example.org
  plugins:
    - name: rate-limiting
      _config: rate-limiting-one
  routes:
  - name: sample
    paths:
    - /sample
```

and this is the error I got:

```cli
Error: validate entity 'plugins (rate-limiting)': HTTP status 400 (message: "schema violation (at least one of these fields must be non-empty: 'config.second', 'config.minute', 'config.hour', 'config.day', 'config.month', 'config.year')")
```

Furthermore the issue appears with Kong 2.7 and earlier versions.

Daniel Schniepp daniel.schniepp@daimler.com, Mercedes-Benz Mobility AG on behalf of Daimler TSS GmbH.
