### ISSUE TITLE
decK de-duplicate plugin remove fields

### ISSUE THREAD

**Issue by tvd2** [Kong/deck#597]
I tried to use de-dup plugins as below config -- for plugin _request-transformer_

```
__plugin_configs:
  rqst-transform-api:
    add:
      headers:
      - service-api-key:abcdef
      body: []
      querystring: []_
```

In the route plugin, I also updated as:

```
_
plugins:        
          - name: request-transformer
             _config: rqst-transform-api
_
```

However, when I tried with Diff, I can see the field `service-api-key` will be delete

```
---
updating plugin request-transformer for route 97952f78-4793-4d12-af6d-23af83f75053  {
   "config": {
     "add": {
       "body": [
       ],
       "headers": [
**-        "service-api-key:abcdef"**
       ],
       "querystring": [
       ]
     },
     "append": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ]
     },
     "http_method": null,
     "remove": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ]
     },
     "rename": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ]
     },
     "replace": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ],
       "uri": null
     }
   },
   "enabled": true,
   "id": "0b532a56-57e9-4ab4-8ced-dc73e60c284b",
   "name": "request-transformer",
-  "protocols": [
-    "grpc",
-    "grpcs",
-    "http",
-    "https"
-  ],
   "route": {
     "id": "97952f78-4793-4d12-af6d-23af83f75053"
   }
 }
---
```

The protocols are default, so not to worry much, but the service-api-key field remove as the highlight, I also tried with sync and yes, the field was also deleted in the plugin after syncing. Also, happen for another plugin _key-auth_

I'm using decK 1.11

**Comment by GGabriele** [comment]
Hello @tvd2 ,

this is related to [this other issue](https://github.com/Kong/deck/issues/593) that was recently opened, and that was fixed with https://github.com/Kong/deck/pull/594

Latest `deck` works as expected. We will do a patch release (v.1.11.1) shortly.

```
_plugin_configs:
  rqst-transform-api:
    add:
      headers:
      - service-api-key:abcdef
      body: []
      querystring: []

services:
- name: sample
  url: https://example.org
  plugins:
    - name: request-transformer
      _config: rqst-transform-api
```

```
$ deck sync
updating plugin request-transformer for service 0f82b337-05cb-4e23-8887-46f49075bc96  {
   "config": {
     "add": {
       "body": [
       ],
       "headers": [
         "service-api-key:abcdef"
       ],
       "querystring": [
       ]
     },
     "append": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ]
     },
     "http_method": null,
     "remove": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ]
     },
     "rename": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ]
     },
     "replace": {
       "body": [
       ],
       "headers": [
       ],
       "querystring": [
       ],
       "uri": null
     }
   },
   "enabled": true,
   "id": "ceb7ce6b-ae4c-47b6-b573-102507a7980a",
   "name": "request-transformer",
-  "protocols": [
-    "grpc",
-    "grpcs",
-    "http",
-    "https"
-  ],
   "service": {
     "id": "0f82b337-05cb-4e23-8887-46f49075bc96"
   }
 }

Summary:
  Created: 0
  Updated: 1
  Deleted: 0
```
