### ISSUE TITLE
Deck sync does not recognise regex route collissions

### ISSUE THREAD

**Issue by dmortim** [Kong/deck#609]
### Environment
```
Kong Hybrid EE 2.7.1.1

$ deck version
decK v1.11.0 (4235c73)
$ inso --version
2.4.1
``` 
### Issue
If we create a route /example/{id} then in a separate workspace we create /example/{id_2} deck / Kong does not recognise this collision. 

If we do not use parameters or use the same parameters naming we get this output, which is great.
```
while processing event: {Create} route demo_one-example_id-get failed: HTTP status 409 (message: "API route collides with an existing API")
```

### Behaviour
So if we use the following curl command it will always route to /example/{id} i.e. the first one created.
```
curl -k https://${KONG_PROXY_URL}/example/1234
```

### Example configuration
I assume this is happening because the collision matching is based off the .services.routes.paths which appears different because of the parameter naming, yet it is actually the same route. 

Here is the sample of the kong declarative configuration we are applying
``` yaml
# id
services:
  - retries: 5
    name: demo_one
    protocol: https
    host: demo_one.upstream
    port: 443
    path: /
    plugins: []
    routes:
      - request_buffering: true
        response_buffering: true
        path_handling: v0
        https_redirect_status_code: 426
        tags:
          - OAS3_import
          - OAS3file_demo-one.yaml
        name: demo_one-example_id-get
        methods:
          - GET
        paths:
          - /example/(?<id>[^\/]+)$

# id_2
services:
  - retries: 5
    name: demo_one
    protocol: https
    host: demo_one.upstream
    port: 443
    path: /
    plugins: []
    routes:
      - request_buffering: true
        response_buffering: true
        path_handling: v0
        https_redirect_status_code: 426
        tags:
          - OAS3_import
          - OAS3file_demo-one.yaml
        name: demo_one-example_id_2-get
        methods:
          - GET
        paths:
          - /example/(?<id_2>[^\/]+)$
        strip_path: false
```
