### ISSUE TITLE
Deck 1.10.0 : diff without information on prefix path

### ISSUE THREAD

**Issue by cello86** [Kong/deck#625]
Hi all,
we noticed on our production cluster that deck tries to updated on all runs a single routes but we didn't identify the reason of this change. The diff output is:

ok: [prod-server] => {
    "msg": [
        "updating route apisite-internal-all-catch-all  {", 
        "   \"hosts\": [", 
        "     \"test.local"", 
        "   ],", 
        "   \"https_redirect_status_code\": 426,", 
        "   \"id\": \"ed145fed-284b-4d00-af4f-f2e6ede7331d\",", 
        "   \"methods\": [", 
        "     \"DELETE\",", 
        "     \"GET\",", 
        "     \"HEAD\",", 
        "     \"OPTIONS\",", 
        "   ],", 
        "   \"name\": \"apisite-internal-all-catch-all\",", 
        "   \"path_handling\": \"v0\",", 
        "   \"paths\": [", 
        "     \"/\"", 
        "   ],", 
        "   \"preserve_host\": false,", 
        "   \"protocols\": [", 
        "     \"http\"", 
        "   ],", 
        "   \"regex_priority\": 0,", 
        "   \"request_buffering\": true,", 
        "   \"response_buffering\": true,", 
        "   \"service\": {", 
        "     \"id\": \"cd5ac4e8-f8a4-46c5-917a-3e846ec38482\"", 
        "   },", 
        "   \"strip_path\": false,", 
        "   \"tags\": [", 
        "     \"site-internal\"", 
        "   ]", 
        " }", 
        "", 
        "Summary:", 
        "  Created: 0", 
        "  Updated: 1", 
        "  Deleted: 0"
    ]
}

could we execute some checks to identify and identify the drift on the configuration?

Thanks,
Marcello

**Comment by hbagdi** [comment]
@GGabriele There seems to be a false positive diff here.
@cello86 Could you share the YAML file which resulted in this problem and also share the version of Kong and decK that you are running?

**Comment by GGabriele** [comment]
This may be related to [this other one](https://github.com/Kong/deck/issues/503)..

**Comment by cello86** [comment]
Hi @GGabriele @hbagdi 
I tried to replicate the issue and i found the strange behavior. The problem is present on Kong EE 2.5.0 and 2.7.0 with deck 1.9 and 1.10.
I used this file for the test:

```
_format_version: "1.1"
_info:
  select_tags:
  - site-internal
_workspace: $WORKSPACE
services:
- connect_timeout: 60000
  host: localhost
  name: apisite-kong-localinstance
  path: /
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: global-kong-internal-probe
    methods:
    - GET
    paths:
    - /kong-probe.html$
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: false
    plugins:
    - name: request-termination
      _config: request-termination-probe-config
      protocols:
      - http
      - https
      enabled: true
  - hosts:
    - $SITE_API_INTERNAL_HOST
    name: apisite-internal-all-catch-all
    methods:
    - DELETE
    - GET
    - OPTIONS
    - POST
    - HEAD
    paths:
    - /
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: false
    plugins:
    - name: request-termination
      _config: request-termination-all-config
      protocols:
      - http
      - https
      enabled: true
```
The problem is caused by the sorting that deck tries to apply on the list of the "hosts.0.methods" field that is not sorted on the file, but then in the process of being inserted the API admin side are sorted. 

Marcello
