### ISSUE TITLE
Deck Sync Error while processing event {Create} target for upstream failed: HTTP status 405 (message: "<failed to parse response body: invalid character '<' looking for beginning of value>")

### ISSUE THREAD

**Issue by saisatishkarra** [Kong/deck#669]
Versions:

**Deck Version**: decK v1.12.0 (e6da448)
**Kong Gateway Server:**  kong/2.8.0.0-nightly-enterprise-edition

Description:
Unable to create an `upstream` target using deck configuration against kong/2.8.0.0-nightly-enterprise-edition
Deck validates and diff seems to successfully report the  200 status for the successful creation of all resources. 
Upon running deck sync, the target creation seems to fail with 405:
```
Error: 1 errors occurred:
        while processing event: {Create} target httpbin.org:443 for upstream d38e8b0f-1c94-4851-8324-cc73fa6e9427 failed: HTTP status 405 (message: "<failed to parse response body: invalid character '<' looking for beginning of value>")
```

![Screen Shot 2022-05-03 at 4 49 38 PM](https://user-images.githubusercontent.com/29549979/166573584-242abf5b-7914-402f-b5c4-dd6b9f0451cc.png)
![Screen Shot 2022-05-03 at 4 55 07 PM](https://user-images.githubusercontent.com/29549979/166573590-2828a714-41af-4944-b1c5-763098f553ca.png)

**Deck Configuration:**
```
_format_version: "1.1"
consumers:
- custom_id: j.doe
  tags:
  - test
  username: john_doe
plugins:
- config:
    anonymous: null
    hide_credentials: false
  enabled: true
  name: basic-auth
  protocols:
  - grpc
  - grpcs
  - http
  - https
  tags:
  - test
- config:
    allow:
    - 0.0.0.0/32
    deny: null
    message: null
    status: null
  consumer: john_doe
  enabled: true
  name: ip-restriction
  protocols:
  - grpc
  - grpcs
  - http
  - https
  route: testRoute
  service: testService
  tags:
  - test
- config:
    anonymous: null
    claims_to_verify: null
    cookie_names: []
    header_names:
    - authorization
    key_claim_name: iss
    maximum_expiration: 0
    run_on_preflight: true
    secret_is_base64: false
    uri_param_names:
    - jwt
  enabled: true
  name: jwt
  protocols:
  - grpc
  - grpcs
  - http
  - https
  tags:
  - test
services:
- connect_timeout: 60000
  host: exampleUpstream
  name: testService
  path: /anything
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - headers:
      X-Powered-By:
      - Kong
    https_redirect_status_code: 426
    name: testRoute
    path_handling: v0
    paths:
    - /api
    - /test
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
    tags:
    - test
  tags:
  - test
  write_timeout: 60000
upstreams:
- algorithm: round-robin
  hash_fallback: none
  hash_on: none
  hash_on_cookie_path: /
  healthchecks:
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 0
        successes: 0
      http_path: /
      https_verify_certificate: true
      timeout: 1
      type: http
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        interval: 0
        tcp_failures: 0
        timeouts: 0
    passive:
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 0
      type: http
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 500
        - 503
        tcp_failures: 0
        timeouts: 0
    threshold: 0
  name: exampleUpstream
  slots: 10000
  targets:
  - target: httpbin.org:80
    weight: 100

```
