### ISSUE TITLE
Show meaningful validation errors

### ISSUE THREAD

**Issue by marceloboeira** [Kong/deck#932]
When validation errors occur for properties of some entities, like routes, the response is generic and not really useful to target the issue:

For example, imagine this:

```yaml
---
_format_version: "3.0"

services:
- name: service-x
  enabled: true
  host: service-x
  protocol: tcp
  routes:
  - name: service-x
    protocols:
      - tcp
    hosts:
    - invalid.option.com
```

Running it results on:

```diff
$ deck sync -s "service-x/"

updating route service-x  {
   "name": "service-x",
   "path_handling": "v0",
   "preserve_host": false,
   "protocols": [
     "tcp"
   ],
   "regex_priority": 0,
   "request_buffering": true,
   "response_buffering": true,
   "service": {
     "id": "<REDACTED>",
     "name": "service-x"
   },
   "strip_path": true,
+  "hosts": [
+    "invalid.option.com"
+  ]
 }
Summary:
  Created: 0
  Updated: 0
  Deleted: 0
Error: 1 errors occurred:
	while processing event: {Update} route service-x failed: HTTP status 400 (message: "validation error")
```

The API itself already provides a more meaningful error message, replicating the request on HTTP I can see:

```json
{
  "code":3,
  "message":"validation error",
  "details:  [ 
     { 
        "@type": "type.googleapis.com/kong.admin.model.v1.ErrorDetail",
        "type": "ERROR_TYPE_ENTITY", 
        "messages":
             [
               "when protocol has 'tcp', 'tls', 'tls_passthrough' or 'udp', 'methods', 'hosts', 'paths', 'headers' cannot be set"
             ]
    }
  ]
}
```

Is it on the roadmap to somehow expand the error message to integrate with the response? If yes, are you open to MRs on that?
